#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# echo \"[Husky] pre-push\"
# npx lint-staged

git add .
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-push hook...${no_color}\n"
echo -e "${green} [Husky] pre-push\n"
npx lint-staged
echo -e "${green}Git pre-push hook was successful!${no_color}\n"